# Generated by Django 4.1 on 2022-08-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_alter_document_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
