# Generated by Django 4.1 on 2022-08-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_delete_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='image',
            new_name='images',
        ),
    ]
