# Generated by Django 4.1 on 2022-08-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_alter_document_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='story',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
